### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by vvatelot** [cnumr/ecoindex-browser-plugin#54]
- [ ] Extract common functions (API calls, set badge, update local storage...)
- [ ] Update badge status after an analysis have been made in the popup

**Comment by jpkha** [comment]
What about refactoring the code by changing polyfill file name and put inside all the common function, variable we have between popup.js and background.js ? So we got one file which holds the logic and only one import in popup and background js ?

**Comment by vvatelot** [comment]
GO GO GO !
